title:            devkev
description:      I'm ruby, clojure, web developer from Leipzig. I write about other blog post, articles and conference talks I find worth reading.
url:              # devkev.de
signoff:          Kevin
disqus_shortname: devkev
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         Blog
    url:          /
  - name:         About
    url:          /about

permalink: /blog/:title
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - .ruby-version
  - CNAME
